apiVersion: v1
kind: Service
current-context: default
metadata:
  name: kubeservice
spec:
  selector:
    app: codershop
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: codershop
  template:
    metadata:
      labels:
        app: codershop
    spec:
      containers:
        - name: kubecontainers
          image: dacelisl/codershop:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
